// SPDX-License-Identifier: MIT
pragma solidity ^0.8.9;

 
/// @custom:security-contact soporte@comunyt.com
contract ERC1066 {

    // Uses status codes from ERC-1066
    bytes1 internal  constant STATUS_DISALLOWED = 0x10;   // 0001 0000
    bytes1 internal  constant STATUS_ALLOWED = 0x11;      // 0001 0001
    bytes1 internal  constant STATUS_INSUFICIENTFUNDS = 0x54 ;
    bytes1 internal  constant STATUS_TRANSFERVOLUMEEXCEEDED = 0x56 ;

    /// @dev ERC-1066 status codes encoded as human-readable enums
    enum Status {

        // 0x0*
        Failure,
        Success,
        AwatingOthers,
        Accepted,
        LowerLimit,
        RecieverActionRequested,
        UpperLimit,
        RESERVEDx07,
        Inapplicable,
        RESERVEDx09,
        RESERVEDx0A,
        RESERVEDx0B,
        RESERVEDx0C,
        RESERVEDx0D,
        RESERVEDx0E,
        Informational,

        // 0x1*
        Disallowed_Stop,
        Allowed_Go,
        AwaitingOthersPermission,
        PermissionRequested,
        TooOpen_Insecure,
        NeedsYourPermission_RequestForContinuation,
        Revoked_Banned,
        RESERVEDx17,
        NotApplicatableToCurrentState,
        RESERVEDx19,
        RESERVEDx1A,
        RESERVEDx1B,
        RESERVEDx1C,
        RESERVEDx1D,
        RESERVEDx1E,
        PermissionDetails_ControlConditions,

        // 0x2*
        NotFound_Unequal_OutOfRange,
        Found_Equal_InRange,
        AwaitingMatch,
        MatchRequestSent,
        BelowRange_Underflow,
        RequestForMatch,
        Above_Range_Overflow,
        RESERVEDx27,
        Duplicate_Conflict_Collision,
        RESERVEDx29,
        RESERVEDx2A,
        RESERVEDx2B,
        RESERVEDx2C,
        RESERVEDx2D,
        RESERVEDx2E,
        MatchingInformation,

        // 0x3*
        SenderDisagrees_Nay,
        SenderAgrees_Yea,
        AwaitingRatification,
        OfferSent_Voted,
        QuorumNotReached,
        ReceiversRatificationRequested,
        OfferOrVoteLimitReached,
        RESERVEDx37,
        AlreadyVoted,
        RESERVEDx39,
        RESERVEDx3A,
        RESERVEDx3B,
        RESERVEDx3C,
        RESERVEDx3D,
        RESERVEDx3E,
        NegotiationRules_ParticipationInformation,

        // 0x4*
        Unavailable,
        Available,
        Paused,
        Queued,
        NotAvailableYet,
        AwaitingYourAvailability,
        Expired,
        RESERVEDx47,
        AlreadyDone,
        RESERVEDx49,
        RESERVEDx4A,
        RESERVEDx4B,
        RESERVEDx4C,
        RESERVEDx4D,
        RESERVEDx4E,
        AvailabilityRules_Information,

        // 0x5*
        TransferFailed,
        TransferSuccessful,
        AwaitingPaymentFromOthers,
        Hold_Escrow,
        InsufficientFunds,
        FundsRequested,
        TransferVolumeExceeded,
        RESERVEDx57,
        FundsNotRequired,
        RESERVEDx59,
        RESERVEDx5A,
        RESERVEDx5B,
        RESERVEDx5C,
        RESERVEDx5D,
        RESERVEDx5E,
        FinancialInformation,

        // 0x6*
        RESERVEDx60,
        RESERVEDx61,
        RESERVEDx62,
        RESERVEDx63,
        RESERVEDx64,
        RESERVEDx65,
        RESERVEDx66,
        RESERVEDx67,
        RESERVEDx68,
        RESERVEDx69,
        RESERVEDx6A,
        RESERVEDx6B,
        RESERVEDx6C,
        RESERVEDx6D,
        RESERVEDx6E,
        RESERVEDx6F,

        // 0x7*
        RESERVEDx70,
        RESERVEDx71,
        RESERVEDx72,
        RESERVEDx73,
        RESERVEDx74,
        RESERVEDx75,
        RESERVEDx76,
        RESERVEDx77,
        RESERVEDx78,
        RESERVEDx79,
        RESERVEDx7A,
        RESERVEDx7B,
        RESERVEDx7C,
        RESERVEDx7D,
        RESERVEDx7E,
        RESERVEDx7F,

        // 0x8*
        RESERVEDx80,
        RESERVEDx81,
        RESERVEDx82,
        RESERVEDx83,
        RESERVEDx84,
        RESERVEDx85,
        RESERVEDx86,
        RESERVEDx87,
        RESERVEDx88,
        RESERVEDx89,
        RESERVEDx8A,
        RESERVEDx8B,
        RESERVEDx8C,
        RESERVEDx8D,
        RESERVEDx8E,
        RESERVEDx8F,

        // 0x9*
        RESERVEDx90,
        RESERVEDx91,
        RESERVEDx92,
        RESERVEDx93,
        RESERVEDx94,
        RESERVEDx95,
        RESERVEDx96,
        RESERVEDx97,
        RESERVEDx98,
        RESERVEDx99,
        RESERVEDx9A,
        RESERVEDx9B,
        RESERVEDx9C,
        RESERVEDx9D,
        RESERVEDx9E,
        RESERVEDx9F,

        // 0xA*
        ApplicationSpecificFailure,
        ApplicationSpecificSuccess,
        ApplicationSpecificAwatingOthers,
        ApplicationSpecificAccepted,
        ApplicationSpecificLowerLimit,
        ApplicationSpecificRecieverActionRequested,
        ApplicationSpecificUpperLimit,
        RESERVEDxA7,
        ApplicationSpecific_Inapplicable,
        RESERVEDxA9,
        RESERVEDxAA,
        RESERVEDxAB,
        RESERVEDxAC,
        RESERVEDxAD,
        RESERVEDxAE,
        ApplicationSpecificInformational,

        // 0xB*
        RESERVEDxB0,
        RESERVEDxB1,
        RESERVEDxB2,
        RESERVEDxB3,
        RESERVEDxB4,
        RESERVEDxB5,
        RESERVEDxB6,
        RESERVEDxB7,
        RESERVEDxB8,
        RESERVEDxB9,
        RESERVEDxBA,
        RESERVEDxBB,
        RESERVEDxBC,
        RESERVEDxBD,
        RESERVEDxBE,
        RESERVEDxBF,

        // 0xC*
        RESERVEDxC0,
        RESERVEDxC1,
        RESERVEDxC2,
        RESERVEDxC3,
        RESERVEDxC4,
        RESERVEDxC5,
        RESERVEDxC6,
        RESERVEDxC7,
        RESERVEDxC8,
        RESERVEDxC9,
        RESERVEDxCA,
        RESERVEDxCB,
        RESERVEDxCC,
        RESERVEDxCD,
        RESERVEDxCE,
        RESERVEDxCF,

        // 0xD*
        RESERVEDxD0,
        RESERVEDxD1,
        RESERVEDxD2,
        RESERVEDxD3,
        RESERVEDxD4,
        RESERVEDxD5,
        RESERVEDxD6,
        RESERVEDxD7,
        RESERVEDxD8,
        RESERVEDxD9,
        RESERVEDxDA,
        RESERVEDxDB,
        RESERVEDxDC,
        RESERVEDxDD,
        RESERVEDxDE,
        RESERVEDxDF,

        // 0xE*
        DecryptFailure,
        DecryptSuccess,
        AwaitingOtherSignaturesOrKeys,
        Signed,
        Unsigned_Untrusted,
        SignatureRequired,
        KnownToBeCompromised,
        RESERVEDxE7,
        AlreadySigned_NotEncrypted,
        RESERVEDxE9,
        RESERVEDxEA,
        RESERVEDxEB,
        RESERVEDxEC,
        RESERVEDxED,
        RESERVEDxEE,
        Cryptography_ID_ProofMetadata,

        // 0xF*
        OffChainFailure,
        OffChainSuccess,
        AwatingOffChainProcess,
        OffChainProcessStarted,
        OffChainServiceUnreachable,
        OffChainActionRequired,
        OffChainExpiry_LimitReached,
        RESERVEDxF7,
        DuplicateOffChainRequest,
        RESERVEDxF9,
        RESERVEDxFA,
        RESERVEDxFB,
        RESERVEDxFC,
        RESERVEDxFD,
        RESERVEDxFE,
        OffChainInformation
    }
}